title: Béatrice Mazoyer
logo: /assets/img/photoCV.jpg
cv: /assets/img/cv_beatrice_mazoyer.pdf
description: PhD student at CentraleSupelec
mail: beatrice.mazoyer[at]centralesupelec.fr
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
