title: Béatrice Mazoyer
logo: /assets/img/photoCV.jpeg
cv: /assets/img/cv_beatrice_mazoyer.pdf
paper: /assets/img/cage_herve_mazoyer_Twitter_propagation_2020_10.pdf
description:
mail: beatrice.mazoyer[at]sciencespo.fr
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
