title: Béatrice Mazoyer
logo: /assets/img/photoCV.jpg
cv: /assets/img/cv_beatrice_mazoyer.pdf
description: PhD student at Institut National de l'Audiovisuel
street: 18 avenue des Frères Lumière
city: 94360 Bry-sur-Marne, France
mail: bmazoyer[at]ina.fr
show_downloads: false
google_analytics:
theme: jekyll-theme-minimal
